//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiumJustMuesliApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JustMuesliDataBaseEntities1 : DbContext
    {
        public JustMuesliDataBaseEntities1()
            : base("name=JustMuesliDataBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Ingredient> Ingredient { get; set; }
        public virtual DbSet<Muesli> Muesli { get; set; }
        public virtual DbSet<MuesliIngredient> MuesliIngredient { get; set; }
        public virtual DbSet<MuesliMix> MuesliMix { get; set; }
        public virtual DbSet<MuesliMixMuesli> MuesliMixMuesli { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderMuesliMixes> OrderMuesliMixes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
