//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiumJustMuesliApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muesli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Muesli()
        {
            this.MuesliIngredient = new HashSet<MuesliIngredient>();
            this.MuesliMixMuesli = new HashSet<MuesliMixMuesli>();
        }
    
        public int Id { get; set; }
        public string NameEN { get; set; }
        public string NameDE { get; set; }
        public double Protein { get; set; }
        public double Carbohydrates { get; set; }
        public double Fat { get; set; }
        public int PortionSize { get; set; }
        public double Price { get; set; }
        public int TypeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuesliIngredient> MuesliIngredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuesliMixMuesli> MuesliMixMuesli { get; set; }
    }
}
